n1 = input('Digite algo: ')
print(type(n1))
print("É numérico? ", n1.isnumeric())
print("É alfabético? ", n1.isalpha())
print("É alfanumérico? ", n1.isalnum())
print("Só tem espaços? ", n1.isspace())
print("Está em minúsculas? ", n1.isupper())
print("Está em maiúsculas? ", n1.islower())
print("Está capitalizada? ", n1.istitle())
